CREATE TYPE class_skills as ENUM (
  'assassinSkills',
  'druidSkills',
  'gladSkills',
  'hunterSkills',
  'mageSkills',
  'shamanSkills',
  'warlockSkills',
  'warriorSkills'
);

CREATE TYPE class_clatters as ENUM (
  'assassinClatters',
  'druidClatters',
  'gladClatters',
  'hunterClatters',
  'mageClatters',
  'shamanClatters',
  'warlockClatters',
  'warriorClatters'
);

CREATE TYPE class_tempers as ENUM (
  'assassinTempers',
  'druidTempers',
  'gladTempers',
  'hunterTempers',
  'mageTempers',
  'shamanTempers',
  'warlockTempers',
  'warriorTempers'
);

CREATE TYPE class_whishes as ENUM (
  'assassinWishes',
  'druidWishes',
  'gladWishes',
  'hunterWishes',
  'mageWishes',
  'shamanWishes',
  'warlockWishes',
  'warriorWishes'
);

CREATE TYPE class_attributes as ENUM (
  'assassinAttributes',
  'druidAttributes',
  'gladAttributes',
  'hunterAttributes',
  'mageAttributes',
  'shamanAttributes',
  'warlockAttributes',
  'warriorAttributes'
);

CREATE TYPE class_name as ENUM (
  'Assassin',
  'Druid',
  'Gladiator',
  'Hunter',
  'Mage',
  'Shaman',
  'Warlock',
  'Warrior'
);

CREATE TABLE ulala_guide_builds (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  class class_name,
  clatters class_clatters,
  skills class_skills,
  tempers class_tempers,
  whishes class_whishes,
  attributes class_attributes
);